from collections.abc import Iterator, Mapping
from datetime import datetime
from pathlib import Path
from typing import Any, SupportsFloat

import polars as pl
from _typeshed import StrPath

from ._run import Run
from .metrics import MetricsLike

run: Run

# region Lifecycle

def start() -> None: ...
def end(exc: BaseException | None = None) -> None: ...

# endregion Lifecycle

# region Metrics

def get_step() -> int: ...
def set_step(step: int) -> None: ...
def get_metric(name: str) -> pl.DataFrame: ...
def log_metric(
    name: str,
    value: SupportsFloat,
    *,
    step: int | None = None,
    time: datetime | None = None,
) -> None: ...
def get_metrics(metrics: Iterator[str] | None = None) -> pl.DataFrame: ...
def log_metrics(
    metrics: MetricsLike, *, step: int | None = None, time: datetime | None = None
) -> None: ...

# endregion Metrics

# region Assets

def input(path: StrPath, *, metadata: Mapping[str, Any] | None = None) -> Path: ...  # noqa: A001
def output(
    path: StrPath, *, metadata: Mapping[str, Any] | None = None, mkdir: bool = True
) -> Path: ...
def temp(
    path: StrPath,
    *,
    metadata: Mapping[str, Any] | None = None,
    mkdir: bool = True,
) -> Path: ...
def log_asset(path: StrPath, metadata: Mapping[str, Any] | None = None) -> None: ...
def log_input(path: StrPath, metadata: Mapping[str, Any] | None = None) -> None: ...
def log_output(path: StrPath, metadata: Mapping[str, Any] | None = None) -> None: ...
def log_temp(path: StrPath, metadata: Mapping[str, Any] | None = None) -> None: ...

# endregion Assets

# region Logging

def get_other(name: str) -> Any: ...
def log_other(name: str, value: Any) -> None: ...
def get_others() -> dict[str, Any]: ...
def log_others(others: Mapping[str, Any]) -> None: ...
def get_param(name: str) -> Any: ...
def log_param(name: str, value: Any) -> None: ...
def get_params() -> dict[str, Any]: ...
def log_params(params: Mapping[str, Any]) -> None: ...

# endregion Logging
