from typing import Any, Protocol


class ParamPluginProtocol(Protocol):
    def log_param(self, name: str, value: Any) -> None: ...
    def log_params(self, params: dict[str, Any]) -> None: ...


class OtherPluginProtocol(Protocol):
    def log_other(self, name: str, value: Any) -> None: ...
    def log_others(self, others: dict[str, Any]) -> None: ...
